add 'set' and 'clear' message to [vcf~]
pure-data/pure-data pull request #2439
Opened 2024-09-21 12:58 UTC by no382001

related to #2438

2024-09-21 13:20 UTC, porres commented
hi, I don;t think we need a 'set' message, right? that's for lower level filters.

would you considering just implementing a 'clear' message?

2024-09-21 13:34 UTC, no382001 commented
sure, i just added that bc of the issue's wording.

2024-09-23 07:06 UTC, umlaeute requested changes
the `clear` message for other filters only clear the hidden internal state, not the parameters set from outside:
- https://github.com/pure-data/pure-data/blob/177350fc4999b74ea28a12ba2981baa6ae04c6f0/src/d_filter.c#L122-L125
- https://github.com/pure-data/pure-data/blob/177350fc4999b74ea28a12ba2981baa6ae04c6f0/src/d_filter.c#L165-L168
- https://github.com/pure-data/pure-data/blob/177350fc4999b74ea28a12ba2981baa6ae04c6f0/src/d_filter.c#L320-L323
- ...

so i think we shoud do the same here (which basically boils down to leaving the `x_f` ontouched.

2024-09-23 11:24 UTC, umlaeute approved these changes

2024-10-28 13:12 UTC, merged