Add -alsaname command line flag to allow Pd to use unique Alsa midi port names
pure-data/pure-data pull request #2463
Opened 2024-10-19 22:31 UTC by tstex

Fix for: https://github.com/pure-data/pure-data/issues/2462

2024-10-21 09:36 UTC, umlaeute commented
i wonder whether we shouldn't just re-use the `-jackname` for this.

obviously the name of the flag is sub-optimal (there's no JACK), but maybe the solution is to just rename the flag to `-devicename` (keeping `-jackname` as an alias).

2024-10-21 17:53 UTC, tstex commented
I agree that is a good idea. I believe I tried that initially, but ran into problems. Let me try again tonight after work to verify.

2024-10-21 19:59 UTC, reduzent commented
The flag `-jackname` does not only set the jack client name, but it implicitly switches the audio backend to JACK. I think a new flag like `-devicename` that only sets the name (for whatever audio or MIDI backend) would make a lot of sense and would allow a better behavior without breaking backwards compatibility.

2024-10-21 22:57 UTC, tstex commented
That kind of makes -jackname redundant in some situations yes? How do we resolve situations where the user uses both flags - but with different values?

I'll look at re-using the jackname value shortly. Are there any other use cases for the more generic -devicename on other platforms etc?

As an aside, I don't think jackname should set or switch the backend, but backwards compatibility seems to be highly prized.

2024-10-22 05:23 UTC, reduzent commented
> As an aside, I don't think jackname should set or switch the backend, but backwards compatibility seems to be highly prized.

I absolutely agree on both points.

2024-10-22 05:59 UTC, umlaeute commented
> Hmm. Ok. I remember why I didn't re-use -jackname now. Linkage hell. Makefile changes: (USEAPI_JACK in USEAPI_ALSA code). Much harder (impossible?) to do cleanly from a code point of view.

Nah, much simpler. 
`-devicename` sets an API independent name. As such, it *must not* be depending on any preprocessor define like `USEAPI_JACK` or the like. 
It will simply set a global symbol, that can then be used by any API that requires it (Jack, alsa-midi, futuresound,...)

> As an aside, I don't think jackname should set or switch the backend, but backwards compatibility seems to be highly prized.

I agree with the former.
Personally I could happily  live with `-jackname` not setting the backend. 
Iirc, the current behaviour is not documented (at least I hope so. There's a tendency to document every voidness, turning arbitrary (and not well-thought-of) decisions into canonical and expected behaviour), so we could just regard it as a bug. 
It's easy (and backward compatible) enough to just add an additional "-jack" flag. 
I *would* keep the compost flag name ("-jackname") around, so that startup scripts don't start to fail.

2024-10-22 06:36 UTC, reduzent commented
I fully agree. I also rather would have `-jackname` not implicitly set the back-end. What I meant to say: I fear backwards compatibility concerns (I don't agree with them).

2024-10-22 07:57 UTC, umlaeute requested changes
instead of writing to an API-specific variable, i would instead use a global (but private) `sys_devicename[MAXPDSTRING]`  that get's initialized to `"Pure Data"` (or `"pure_data"`, but I'd actually prefer the former even if the rename breaks my qjackctl patchbays).

than JACK, or ALSA or whoever wants can use this name (as is, without having to check for emptiness).

2024-10-22 07:57 UTC, umlaeute commented on src/s_midi_alsa.c
> +    post("Alsa MIDI client name:%s", alsa_client_name);
this debugging output shouldn't be here

2024-10-23 03:45 UTC, closed without merging

2024-10-23 21:23 UTC, umlaeute commented
why has this PR been closed?

2024-10-23 22:31 UTC, tstex commented
I cleaned up my git history - which inadvertently closed the PR. I will
make a new one. I'm still working on it. There will be another one
involving autoconf probably. CFLAGS includes both -o0 and -o2 at present,
so the things I'm trying to look at in GDB have been optimized away. It's
been quite the side track. :D

But the pd code is written. I just need to debug this last thing....

On Wed, Oct 23, 2024, 2:23 PM umläute ***@***.***> wrote:

> why has this PR been closed?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/pure-data/pure-data/pull/2463#issuecomment-2433490180>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAJTRAXTZI7SO2ST73FURYLZ5AHVTAVCNFSM6AAAAABQH4D3X6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDIMZTGQ4TAMJYGA>
> .
> You are receiving this because you modified the open/close state.Message
> ID: ***@***.***>
>